plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.6
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

# レイアウト系
Layout/LineLength:
  Max: 140

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true

Layout/CommentIndentation:
  Enabled: true

# メトリクス系
Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'

# スタイル系
Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/RedundantConstantBase:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

# Rails 専用
Rails/SafeNavigation:
  Enabled: false

# Bundler
Bundler/OrderedGems:
  Enabled: true

# ドキュメント系
Style/Documentation:
  Enabled: false